### ISSUE TITLE
Region Activity 

### ISSUE THREAD

**Issue by pawankhandal52** [UdacityAndroidDevScholarship/explore-india#18]
## I want to work on a Region Activity. I will design this screen according to Mockup.

**Comment by derrickabreo** [comment]
I am interested in this too.

**Comment by Aaklii** [comment]
@pawankhandal52 @derrickabreo you can design mockup and post them in app channel/

**Comment by akshaychopra96** [comment]
In region Activity, what do we want to show? Can you please explain briefly?

**Comment by theshivamlko** [comment]
@akshaychopra96 soon Region Activity design will be published
