### ISSUE TITLE
google-services file missing in latest master

### ISSUE THREAD

**Issue by sayaMahi** [UdacityAndroidDevScholarship/explore-india#19]
![explore-india____documents_android_exercises_udacity_collab_explore-india_](https://user-images.githubusercontent.com/6975401/38729523-dbe0f990-3f30-11e8-8d34-37d9afa02db7.jpg)

I have just forked master and opened the project. It says, google-services.json file is missing under .../app/.

**Comment by sidhuparas** [comment]
Read README carefully and close the issue! https://github.com/UdacityAndroidDevScholarship/explore-india/blob/master/README.md

**Comment by vvkvivekl** [comment]
Read README.md before going further.. Most of are mentioned there..

close this issue..
