### ISSUE TITLE
Signup on the app just using mobile number

### ISSUE THREAD

**Issue by S2606** [UdacityAndroidDevScholarship/explore-india#34]
**Summary:**

User can signup with just their mobile number?? 

**Steps to reproduce:**

How can we reproduce the issue?

**Expected behaviour:**

Complete the signup process

**Observed behaviour:**

Only signup using google account

**Comment by S2606** [comment]
I am claiming this issue

**Comment by geekanamika** [comment]
@S2606 Hold on this issue. We'll be creating issues with full description. Thanks :)
