### ISSUE TITLE
Fix the toolbar bug

### ISSUE THREAD

**Issue by geekanamika** [UdacityAndroidDevScholarship/explore-india#37]
**Summary:**
home button is disabled

**Steps to reproduce:**
* Add any line
* remote any line 

**Expected behaviour:**

**Observed behaviour:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by harikautilya** [comment]
@geekanamika if it's okie close this issue...just cleaning  up the code base

**Comment by geekanamika** [comment]
Yeah, We can close it.
