### ISSUE TITLE
Location Permission at welcome screen

### ISSUE THREAD

**Issue by RachnaShriwas** [UdacityAndroidDevScholarship/explore-india#4]
Check on welcome screen whether location permission is granted to the app. If not then request user to give the permission.

**Comment by RachnaShriwas** [comment]
I have written the code for this issue and created a pull request for it. I'll close the issue as soon as the pull request gets merged.

**Comment by Rondaul** [comment]
I have worked on providing permision for external storage at runtime for the first time. So, this is very much similar. I would love to work on this issue.

**Comment by geekanamika** [comment]
@Rondaul @RachnaShriwas  Can both of you discuss it in slack? Or update the issue with current issue template. Anyone of you can work on it, we need to discuss it before assigning it. Thank you.

**Comment by Rondaul** [comment]
@geekanamika actually i have already worked on it and I have created the pull request too.

**Comment by geekanamika** [comment]
@Rondaul We're setting up the MVP pattern for application. We'll be accepting PRs depending on it. Please claim issues created in upcoming days. Thank you.
