### ISSUE TITLE
Package names should be in all lowercase.

### ISSUE THREAD

**Issue by erzohrakhan** [UdacityAndroidDevScholarship/explore-india#41]
**Summary:**

As per the Google Java Style guidelines Package names should be in all lowercase. But in this code repo, this standard is not followed. 

**Steps to reproduce:**
NA

How can we reproduce the issue?
NA

**Expected behaviour:**
All the package names should be in lowercase.

What did you expect the app to do?
NA
**Observed behaviour:**
NA

What did you see instead?  Describe your issue in detail here.
NA

**Screenshots:**.
NA

**Comment by harikautilya** [comment]
Duly noted will be making changes soon
