### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by harikautilya** [UdacityAndroidDevScholarship/explore-india#43]
**Summary:**

Design the login screen

**Expected behaviour:**

Match the UI given

**Observed behaviour:**

Nothing 

**Device and Android version:**

Don't add any libraries

**Screenshots:**

Please share if necessary only

**Comment by nishank95** [comment]
Can i work on this

**Comment by harikautilya** [comment]
Sure take a pull tonight at 12 @nishank95

**Comment by nishank95** [comment]
can you tell me where's the link to mockups

**Comment by harikautilya** [comment]
![1 login](https://user-images.githubusercontent.com/17510412/39372542-53dfc516-4a62-11e8-89e2-1f6f3230ec9c.PNG)

**Comment by harikautilya** [comment]
Here is the screen
