### ISSUE TITLE
PlaceFragment

### ISSUE THREAD

**Issue by harikautilya** [UdacityAndroidDevScholarship/explore-india#45]
**Summary:**

PlaceFragment UI and implementation

**Steps to reproduce:**

How can we reproduce the issue?

**Expected behaviour:**

Design the UI and behaviour

**Screenshots:**

if needed

![4 add place](https://user-images.githubusercontent.com/17510412/39393661-7e7a30da-4ae5-11e8-8e51-3df61b6d386a.png)

**Comment by GauravR31** [comment]
Could I get a link to the mockups?

**Comment by nikita1211** [comment]
https://drive.google.com/drive/folders/1UbtI0Wrbqv2Ql5BaL4I4JGXS_WalP2I6?usp=sharing

**Comment by nikita1211** [comment]
https://drive.google.com/drive/folders/1UbtI0Wrbqv2Ql5BaL4I4JGXS_WalP2I6?usp=sharing

**Comment by nikita1211** [comment]
@GauravR31 Would you like to work on this?

**Comment by GauravR31** [comment]
Ok sure. So should I leave issue #47 ?

**Comment by nikita1211** [comment]
@GauravR31 Yes please, leave issue #47 and go for #45

**Comment by GauravR31** [comment]
Ok. Which mockup file am I supposed to follow from the folder you just shared?

**Comment by harikautilya** [comment]
@GauravR31 updated the issue

**Comment by Devesh1396** [comment]
Can I work on this?
