### ISSUE TITLE
MainFragment

### ISSUE THREAD

**Issue by harikautilya** [UdacityAndroidDevScholarship/explore-india#46]
**Summary:**

Main fragment Design and behaviour

**Expected behaviour:**

Design according to UI

**Screenshots:**

if needed

UI

![1 home 1 1](https://user-images.githubusercontent.com/17510412/39394730-126ae8e0-4af3-11e8-8db2-c7019a5d80ac.jpg)

**Comment by Devesh1396** [comment]
What we have to do here? Any mockup UI for this?

**Comment by Devesh1396** [comment]
@harikautilya can I claim this issue? I will be working with one more person. - Divya.

**Comment by Devesh1396** [comment]
Okay! Please provide the resources.

**Comment by voltr0x** [comment]
Can I work on this too?
