### ISSUE TITLE
Add Places Screen

### ISSUE THREAD

**Issue by kamalshree** [UdacityAndroidDevScholarship/explore-india#49]
**Summary:**
Design Add Places Screen.

**Expected behaviour:**
Follow the mockup provided. 
![4 add place](https://user-images.githubusercontent.com/16922933/39392811-63cac8c2-4ada-11e8-9433-d458f8eb70d8.png)

**Device and Android version:**
N/A

**Estimated Time**
36 hours

**Comment by Devesh1396** [comment]
Can I work on this?

**Comment by harikautilya** [comment]
Duplicate of issue https://github.com/UdacityAndroidDevScholarship/explore-india/issues/45

**Comment by harikautilya** [comment]
@Devesh1396 and @kamalshree 
please visit https://github.com/UdacityAndroidDevScholarship/explore-india/issues/45
closing this issue soon
