### ISSUE TITLE
Place Details Screen

### ISSUE THREAD

**Issue by kamalshree** [UdacityAndroidDevScholarship/explore-india#51]
**Summary:**

Design Add Place Details Screen.

**Expected behaviour:**

Follow the mockup provided.

**Device and Android version:**
N/A

![11 place detail](https://user-images.githubusercontent.com/3199282/39399397-cf4c0cfe-4aea-11e8-8b17-4e1f69327e32.png)

**Comment by kamalshree** [comment]
Can I work on this issue?

**Comment by Rondaul** [comment]
@kamalshree yes, I think its fine. You can start working on it. Please follow the design guidelines and refer `ids.xml` for ids for the views. When can you submit your PR?

**Comment by intkhabahmed** [comment]
Hey, can I work on this?

**Comment by Rondaul** [comment]
@intkhabahmed even @kamalshree  wants to work on this. Can you guys collaborate??

**Comment by intkhabahmed** [comment]
So we can both work separately as it will be very difficult to collaborate for a single layout, you can choose whatever you find better

**Comment by Rondaul** [comment]
ok, work single then. whose code is better and organized, we will merge that one. 👍

**Comment by intkhabahmed** [comment]
@Rondaul Will it be a fragment or activity?

**Comment by Rondaul** [comment]
@intkhabahmed it will an activity.

**Comment by intkhabahmed** [comment]
@Rondaul one more doubt, the image is ImageView or RecyclerView as I saw the id for the image in project is places_details_rv_images, and for indicator should I create separate views

**Comment by Rondaul** [comment]
@intkhabahmed oh, sorry and thank you that is actually a viewpager. Use Viewpager and use images in the fragments and use it. I will change it

**Comment by kamalshree** [comment]
@Rondaul Thanks, I have submitted the pull request you can review it.
