### ISSUE TITLE
Place reviews

### ISSUE THREAD

**Issue by vibhuti16** [UdacityAndroidDevScholarship/explore-india#54]
**Summary:**

Get the reviews for a particular place in the details section

What did you expect the app to do?

Show the user reviews for the place when the user clicks on an icon on the details screen

**Screenshots:** - Adding a screen from google results for now

![screenshot_20180429-180338](https://user-images.githubusercontent.com/4936653/39406710-b7fa422a-4bd8-11e8-8d0d-676a1132c810.jpg)

**Comment by vibhuti16** [comment]
place reviews

**Comment by vibhuti16** [comment]
place reviews

**Comment by Rondaul** [comment]
@vibhuti16 currently we haven't planned for this layout and we have a pre-defined UI mocks which we will be following. Maybe in later stage, we will implement this.
