### ISSUE TITLE
Search screen

### ISSUE THREAD

**Issue by vibhuti16** [UdacityAndroidDevScholarship/explore-india#56]
**Summary:**

Design the search screen 

**Expected behaviour:**

Match the UI given

![2 search](https://user-images.githubusercontent.com/4936653/39406941-4a4c05a2-4bdc-11e8-8f81-4fe6b5422342.jpg)

**Comment by nishank95** [comment]
Can I work on this

**Comment by vibhuti16** [comment]
i have started working already

**Comment by vibhuti16** [comment]
https://github.com/UdacityAndroidDevScholarship/explore-india/pull/65 merged. closing the issue.
