### ISSUE TITLE
Liked Places Screen

### ISSUE THREAD

**Issue by kamalshree** [UdacityAndroidDevScholarship/explore-india#59]
**Summary:**

Design Liked Places Screen

**Expected behaviour:**

Follow the mockup provided.

**Observed behaviour:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**
N/A

**Screenshots:**
![4 liked places](https://user-images.githubusercontent.com/3199282/39415480-dbb8a178-4c11-11e8-89a6-6e96b1a842c1.jpg)

**Comment by kamalshree** [comment]
Can I work on this Issue?

**Comment by vishalrao8** [comment]
I want to work on this

**Comment by omi90** [comment]
If this is not assigned to anyone, I would like to work on this issue or would love to help.

**Comment by YuganshT79** [comment]
Can I still work on this?
