### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by theshivamlko** [UdacityAndroidDevScholarship/explore-india#66]
**Summary:**

Design Liked Splash Screen

**Expected behaviour:**

Follow the mockup provided and Animation.
![screenshot_20180503-141314](https://user-images.githubusercontent.com/15983730/39567384-7e4c9d6e-4edc-11e8-92ab-448958d15961.jpg)

**Comment by Devesh1396** [comment]
Can I claim it?

**Comment by theshivamlko** [comment]
@Kautilyahari  I completed the splash pushed in mine master
