### ISSUE TITLE
Showing statusbar on Splash screen.

### ISSUE THREAD

**Issue by pawankhandal52** [UdacityAndroidDevScholarship/explore-india#73]
**Summary:**

On the Master SplashActivity screen not covering all screen it show the statusbar on top.

**Steps to reproduce:**

Simply run app and check the splash screen

**Expected behaviour:**

I think splash screen should cover full screen

**Device and Android version:**
Xiomi Note 4
Android Version 7.1.2

**Screenshots:**
![splash_screen](https://user-images.githubusercontent.com/16113573/39700997-1ca619ca-521d-11e8-99e4-f590faa3e869.png)

I can Fix this issue?

**Comment by geekanamika** [comment]
Valid issue. You can work on this issue :)

**Comment by pawankhandal52** [comment]
@geekanamika I have fixed the issue and send PR for this. You can check on PR List

**Comment by vvkvivekl** [comment]
Already done
