### ISSUE TITLE
Hint text not visible when EditText field is focused -- Add Place Tab

### ISSUE THREAD

**Issue by omi90** [UdacityAndroidDevScholarship/explore-india#75]
**Summary:**

Hint text is white so not visible when EditText field is focused in Add Place Tab.

**Expected behaviour:**

Hint text should be visible when field is focused.

**Device and Android version:**

Moto G4 Plus , Android 7.0
**Screenshots:**

![device-2018-05-07-222323](https://user-images.githubusercontent.com/1911548/39713825-c633e7b0-5245-11e8-800b-f3a114da9c6c.png)

**Comment by vvkvivekl** [comment]
@omi90 If you can, then do it and send PR.

or else mention here.. some can pick and work on same

**Comment by omi90** [comment]
Yes i am working on it.
Will send the PR soon.

**Comment by deepak-thakur** [comment]
is anyone working on it? i wanna do this

**Comment by omi90** [comment]
I have already sent the PR @deepak

**Comment by deepak-thakur** [comment]
then what should i do?

**Comment by vvkvivekl** [comment]
Already done
