### ISSUE TITLE
List of Issues.

### ISSUE THREAD

**Issue by xsahil03x** [UdacityAndroidDevScholarship/explore-india#83]
### 1. [Keyboard overlaps the editText] + [floating hints are invisible] in fragment_place.xml.
<img src="https://user-images.githubusercontent.com/25670178/39729388-30e3b9a4-5279-11e8-8c32-281236f36d2b.png" width="275" height="500">

### 2. Hard to see the entered text in searchView.
<img src="https://user-images.githubusercontent.com/25670178/39729426-64c100a6-5279-11e8-87d2-d568cd148a79.png" width="275" height="500">

### 3. Bottom NavigationView hides the last item of Recyclerview.
<img src="https://user-images.githubusercontent.com/25670178/39729462-96f06ada-5279-11e8-9faa-394bb585adb7.png" width="275" height="500">

### 5. "setOnPageChangeListener" is deprecated.

**Comment by vvkvivekl** [comment]
@xsahil03x see if there is still any issues pending. then do send PR with along with Screen Shot.

**Comment by xsahil03x** [comment]
Will do @VvkLingayat

**Comment by xsahil03x** [comment]
@rdias002 yes you can. Just create a branch from master and send PR 😀

**Comment by rdias002** [comment]
there is another issue, the app name is hidden in searchView. Not a major issue, but just to put it out there.
