### ISSUE TITLE
google-service.json is missing.

### ISSUE THREAD

**Issue by amit88265** [UdacityAndroidDevScholarship/explore-india#9]
While Installing this project on my phone I see this issue. I discussed in slack also and then read some answers on stackoverflow. I got to know that it is a file which may be targeted by some intelligent hackers  etc. , also knew that this file should be same across all projects . So can we receive it to make our development faster.Thanks.

**Comment by theshivamlko** [comment]
This file will be common, provided by moderator, the u can access same firebase DB. It contains only some info about firebase project , but I think firebase console is not easy to hack

**Comment by amit88265** [comment]
Both of your answers are contradicting.

**Comment by theshivamlko** [comment]
We are going to use same database, so wait, will inform u by the tomorrow after discussion with moderator

**Comment by vvkvivekl** [comment]
Hy @amit88265 ,

We are still working on basic structure of project..

For now you will face same issues.. Keep patience..

we will make an announcement once basic structure is ready.. and you can make changes..

**Comment by yhdesai** [comment]
The file can be found in pinned messages in #cp_explore_india Channel
